/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.5 printer.glb --transform
Author: leifer.kopf (https://sketchfab.com/leifer.kopf)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/08-printer-householdpropschallenge-a11b8e0bfc8741f08472c09b10202c75
Title: 08 Printer #HouseholdPropsChallenge
*/

import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useRef } from "react";

export default function Printer(props) {
  const { nodes, materials } = useGLTF("/printer-v2.glb");
  const ref = useRef();
  useFrame(() => {
    ref.current.rotation.y += 0.01;
  });
  return (
    <group {...props} dispose={null} ref={ref}>
      <mesh
        geometry={nodes.Cube_0.geometry}
        material={materials.Grey}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.15, 0.075, 0.06]}
      />
      <mesh
        geometry={nodes.Cube_1.geometry}
        material={materials.Buttons_Black}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.15, 0.075, 0.06]}
      />
      <mesh
        geometry={nodes.Cube_2.geometry}
        material={materials.White}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[0.15, 0.075, 0.06]}
      />
      <mesh
        geometry={nodes.Cube001_0.geometry}
        material={materials.Button_ONOFF}
        position={[0.136, 0.055, 0.06]}
        rotation={[-1.005, 0, 0]}
        scale={[5, 2.5, 2.5]}
      />
    </group>
  );
}
